import { useCommentary } from '../hooks/useCommentary';
import { type Pair } from '../lib/constants';
import { fmtDateTime } from '../lib/format';
import { Card } from './ui';

const FALLBACK =
  'AI market commentary is temporarily unavailable. The figures above reflect the latest market data for this pair.';

export function MarketIntelligence({ pair, now }: { pair: Pair; now: Date }) {
  const { data, isLoading, isError } = useCommentary(pair);

  const text = isLoading
    ? 'Generating market intelligence…'
    : isError
      ? FALLBACK
      : (data ?? FALLBACK);

  return (
    <Card className="ai-card">
      <div className="ai-spark" aria-hidden="true">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">
          <path d="M12 3 13.6 9.4 20 11 13.6 12.6 12 19 10.4 12.6 4 11 10.4 9.4 12 3z" />
          <path d="M19 3l.6 2.4L22 6l-2.4.6L19 9l-.6-2.4L16 6l2.4-.6L19 3z" />
        </svg>
      </div>
      <div className="ai-body">
        <div className="ai-title-row">
          <h3>Market Intelligence</h3>
          <span className="ai-tag">AI · Beta</span>
        </div>
        <p className="ai-text">{text}</p>
        <div className="ai-foot">
          Generated by Colombus Capital AI Engine · model.fx-r1 · <span className="mono">{fmtDateTime(now)}</span>
        </div>
      </div>
    </Card>
  );
}
